language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"

# Set up our virtualenv
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=~/miniconda/bin:$PATH; else export PATH=~/miniconda3/bin/:$PATH; fi
  - conda update --yes conda
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=Pk8rldcpUmf4b8ITeoa7XBYHiAc3LNXlc

# command to install dependencies
install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # install as much as we can via conda
  - conda install --yes pip numpy scipy cython matplotlib nose six scikit-learn ipython networkx pandas tornado statsmodels setuptools pytest pyzmq jinja2 pyyaml
  # Install the rest via pip (brewer2mpl, gspread, seaborn, etc)
  - pip install -r requirements.txt
  # For building the docs
  - pip install sphinx numpydoc sphinx_bootstrap_theme runipy
  - sudo apt-get install pandoc
  - pip install pep8
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install .

# Build documentation
#before_script:
#  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
#    make lint;
#    fi

# command to run tests
script: make coverage
after_success:
  # Push to coveralls.io for test coverage stats
  - coveralls
  # Push to github pages for documentation
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
    cd doc;
    make html;
    cd ../gh-pages;
    git add . ; git commit -m "Update from Travis-CI on $(date)";
    git push -u origin gh-pages;
    fi

# For slack notifications
notifications:
  slack:
    rooms:
    - yeolab:HxLwrd5FGhZQ8SyBD9Fvh3dn#flotilla
env:
  global:
    secure: N8LIn+ZtvaL+j9uHJFRtTWHbJtLk47r+7PUaSPapmpRPkqD4zClwC1+xVrfRXYiTWLVmCMfbcOAjQmZR8OjL8TKD4yGPzXAS5yb9QUhlMBf2is7CECIZQcQ/kht4KGKF72QoRY4r/Eh4NKhayBUWwZmHXd5zIKn8C/irvr+6LBI=
